#include 'totvs.ch'
#include 'fwmvcdef.ch'
#include 'tlpp-core.th'

user function nectarCockipt()

	// incPedido()
    incCliente()

return

static function incCliente()

    dbSelectArea('SA1')
	FWExecView("Incluir","CRMA980",MODEL_OPERATION_INSERT,/*oDlg*/,/*bCloseOnOk*/,/*bOk*/,/*nPercReducao*/)	

return

static function incPedido()

	Local nOpc := 3

	Private cCadastro  := "Atualização de Pedidos de Venda"
	Private INCLUI     := .T.
	Private aRotina    := FWLoadMenuDef( 'MATA410' )

	A410Inclui(/*cAlias*/,/*nReg*/, nOpc /*,lOrcamento,nStack,aRegSCK,lContrat,nTpContr,cCodCli,cLoja,cMedPMS*/)

return
