#include 'totvs.ch'
#include 'fwmvcdef.ch'
#include 'tlpp-core.th'

user function nectarCockipt()

	Local aCoors       := FWGetDialogSize( oMainWnd )
	Local oDlgPrinc    := nil
	Local oPanelUp     := nil
	Local oPanelDown   := nil
	Local oBrowseUp    := nil
	Local oBrowseDown  := nil
	Local oFWLayer     := FWLayer():New()
	Local oBrwRelation := FWBrwRelation():New()

	Define MsDialog oDlgPrinc Title 'Cockipt' From aCoors[1], aCoors[2] To aCoors[3], aCoors[4] Pixel

	oFWLayer:Init( oDlgPrinc, .F., .T. )

	oFWLayer:AddLine( 'UP', 50, .F. )
	oFWLayer:AddCollumn( 'ALL', 100, .T., 'UP' )
	oPanelUp := oFWLayer:GetColPanel( 'ALL', 'UP' )

	oFWLayer:AddLine( 'DOWN', 50, .F. )
	oFWLayer:AddCollumn( 'ALL' , 100, .T., 'DOWN' )
	oPanelDown := oFWLayer:GetColPanel( 'ALL', 'DOWN' )

	oBrowseUp := _oBrowseUp := FWMarkBrowse():New()
	oBrowseUp:SetSemaphore(.T.)
	oBrowseUp:SetOwner( oPanelUp )
	oBrowseUp:SetDescription( "Oportunidades" )
	oBrowseUp:SetAlias( 'ZZY' )
	oBrowseUp:DisableReport()

	oBrowseUp:SetFieldMark( 'ZZY_OK' )
	oBrowseUp:SetAfterMark({||afterMark(),oBrowseUp:Refresh(.F.)})
	oBrowseUp:SetAllMark( {|| .T. } )
	oBrowseUp:setValid( { || validMark() } )

	oBrowseUp:AddLegend( 'ZZY->ZZY_PEDGER' , 'GREEN', 'Pedido Gerado'     )
	oBrowseUp:AddLegend( '!ZZY->ZZY_PEDGER',   'RED', 'Pedido Não Gerado' )

	oBrowseUp:DisableDetails()
	oBrowseUp:ForceQuitButton()
	oBrowseUp:SetMenuDef( 'mnuCockpitZZY' ) // Define de onde virao os botoes deste browse
	oBrowseUp:SetProfileID( '1' ) // identificador (ID) para o Browse
	oBrowseUp:Activate()

	oBrowseDown := FWmBrowse():New()
	oBrowseDown:SetOwner( oPanelDown )
	oBrowseDown:SetDescription( 'Itens Pedido de Venda' )
	oBrowseDown:SetAlias( 'SC6' )
	oBrowseDown:SetFilterDefault( "!EMPTY(SC6->C6_XOPORTU)" )
	oBrowseDown:DisableReport()

	oBrowseDown:AddLegend( 'SC6->( C6_QTDENT == 0 )'         , 'GREEN' , 'Não Faturado'          )
	oBrowseDown:AddLegend( 'SC6->( C6_QTDVEN > C6_QTDENT )'  , 'YELLOW', 'Parcialmente Faturado' )
	oBrowseDown:AddLegend( 'SC6->( C6_QTDVEN == C6_QTDENT )' , 'RED'   , 'Totalmente Faturado'   )

	oBrowseDown:DisableDetails()
	oBrowseDown:SetMenuDef( '' ) // Referencia vazia para que nao exiba nenhum botão
	oBrowseDown:SetProfileID( '2' )
	oBrowseDown:Activate()

	oBrwRelation:AddRelation( oBrowseUp, oBrowseDown, {;
		{ 'C6_FILIAL'  , 'xFilial("ZZY" )' } ,;
		{ 'C6_XOPORTU' , 'ZZY_CODIGO'      } ,;
		{ 'C6_XITOPOR' , 'ZZY_ITEM'        } } )

	oBrwRelation:Activate()

	ACTIVATE MSDIALOG oDlgPrinc CENTERED

return

static function validMark()

	if ZZY->ZZY_PEDGER

		apMsgStop( 'A oportunidade já teve o pedido de venda gerado.', 'Atenção !!!' )

		return .F.

	end if

	if ! ZZY->ZZY_CLICMP

		apMsgStop( 'O contato não foi compatibilizado.', 'Atenção !!!' )

		return .F.

	end if
	
	if ! ZZY->ZZY_PRDCMP

		apMsgStop( 'O produto não foi compatibilizado.', 'Atenção !!!' )

		return .F.

	end if

return .T.

static function afterMark()

	Local aArea         := getArea()
	Local cOportunidade := ZZY->ZZY_CODIGO
	Local cSeek         := xFilial( 'ZZY' ) + cOportunidade
	Local cMark         := ZZY->ZZY_OK

	ZZY->( dbGotop() )

	msSeek( cSeek )

	do while ZZY->( !EOF() .And. ZZY_FILIAL + ZZY_CODIGO == cSeek )

		RecLock( 'ZZY', .F. )
		ZZY->ZZY_OK := cMark
		ZZY->( MsUnlock() )

		ZZY->( dbSkip() )

	end do

	restArea( aArea )

return
